packageVersion: 00
releaseCandidateVersion: 01
workingDir: charts
url:  https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-9.4.2/kube-prometheus-stack-9.4.2.tgz
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: hello
    addCRDValidationToMainChart: true
  # upstreamOptions:
  #   url: local
  # upstreamOptions:
  #   url: packages/rancher-kubecost