sync:
- url: https://github.com/aiyengar2/test-charts.git
  branch: dev-v2.5-source
validate:
- url: https://github.com/aiyengar2/test-charts.git
  branch: main
  dropReleaseCandidates: true
helmRepo:
  cname: charts.rancher.io