# Repository: a repository that contains your forked Helm charts
repository:
  # Owner: the organization or person who owns the chart. Must be a Github user or organization you have permissions to push to
  owner: aiyengar2
  # Name: the name of the repository that contains your forked Helm charts, owned by the user provided above
  name: test-charts

# Helm Repo: the repository that will host your Helm charts, used in the Staging and Live branches
helmRepo:
  # The URL to use as the CNAME for the branch
  url: charts.rancher.io

# Source Branch: a branch that developers push changes to
source:
  name: dev-v2.5-source
  options:
    validate:
    - withBranch: dev-v2.5
    - withBranch: main
      dropReleaseCandidates: true

# Staging Branch: a branch that contains compiled assets and charts merged into the Source branch. Used for testing
staging:
  name: dev-v2.5
  options:
    validate:
    - withBranch: main
      dropReleaseCandidates: true
    sync:
    - withBranch: dev-v2.5-source

# Live Branch: a branch that contains compiled assets and charts ported from the Staging branch. Should never be automated
live:
  name: main
  options:
    sync:
    - withBranch: dev-v2.5
      dropReleaseCandidates: true