packageVersion: 00
releaseCandidateVersion: 00
workingDirectory: charts
url:  https://github.com/kubecost/cost-analyzer-helm-chart.git
subdirectory: cost-analyzer
commit: 0abacd30f00a3e1f02af91d9f9a7dac180362a27
additionalCharts:
- workingDir: chart-copy
  upstreamOptions:
    url:  https://github.com/kubecost/cost-analyzer-helm-chart.git
    subdirectory: cost-analyzer
    commit: 0abacd30f00a3e1f02af91d9f9a7dac180362a27