dependencies:
- name: kube-state-metrics
  version: ""
  repository: file://./charts/kube-state-metrics
  condition: kubeStateMetrics.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: prometheus-node-exporter
  version: ""
  repository: file://./charts/prometheus-node-exporter
  condition: nodeExporter.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
- name: grafana
  version: ""
  repository: file://./charts/grafana
  condition: grafana.enabled
  tags: []
  enabled: false
  importvalues: []
  alias: ""
